export const BEFORE_GET_VALUES = 'BEFORE_GET_VALUES';
export const AFTER_GET_VALUES = 'AFTER_GET_VALUES';
export const AFTER_GET_VALUES_ERROR = 'AFTER_GET_VALUES_ERROR';
export const SET_VALUES = 'SET_VALUES';
